joshmedeski/sesh

zoxide/list.go
Fix #11 
When zoxide isn't installed or doesn't return any results, the zoxide.List command will just return an empty slice
=> Fix zoxide no results

cmds/choose.go, cmds/connect.go, connect/connect.go, session/determine.go, session/path.go, tmux/tmux.go
- Adds the `command` flag to the `connect` command
- Decreases verbosity by substituting `fmt.Println(text)` followed by `os.Exit(1)` with `log.Fatal(text)` (only in edited files)
- Fixes a couple typos (only in edited files)
=> Add "command" flag to "connect" command

session/path.go, zoxide/add.go, zoxide/query.go, zoxide/zoxide.go
Closes #9 
Adds the ability to query zoxide and use the result to generate the session if the connect command's argument is not a path or active session.
=> Zoxide fallback

session/path.go
Closes #33 
Closes #39 
Evaluates symbolic links in the determine path logic to generate the session from the real path (not the symbolically linked path).
=> Evaluate symbolic link real path

.github/workflows/ci-cd.yml
This change will add coverage summary and benchmark results to the output of the ci test run.
=> ci: run benchmark tests and print a coverage summary

cmds/choose.go, cmds/clone.go, cmds/connect.go, connect/connect.go, session/determine.go, tmux/tmux.go, zoxide/add.go
Restructure the code around the connect.Connect method to return errors up the stack for centralized handling. 
fixes: #31
=> refactor: error handling in connect.Connect

cmds/choose.go, cmds/list.go, session/list.go, tmux/list.go, tmux/list_test.go, tmux/tmux.go, tmux/tmux_test.go
Add a flag to the `list` and `choose` commands to provide a means of excluding currently attached sessions when generting a list of current tmux sessions.
closes #50 
<details>
<summary>help output</summary>
<p>
```
❯ go run *.go list --help
NAME:
sesh list - List sessions
USAGE:
sesh list [command options] [arguments...]
OPTIONS:
--tmux, -t           show tmux sessions (default: false)
--zoxide, -z         show zoxide results (default: false)
--hide-attached, -H  don't show currently attached sessions (default: false)
--help, -h           show help
```
```
❯ go run *.go choose -h              
NAME:
sesh choose - Select session
USAGE:
sesh choose [command options] [arguments...]
OPTIONS:
--tmux, -t           show tmux sessions (default: false)
--zoxide, -z         show zoxide results …
```
=> feat: add flag to hide the currently attached session

.github/workflows/ci-cd.yml, tmux/list.go, tmux/list_test.go, tmux/testdata/session_list.txt, tmux/tmux.go
Restructuring the tmux package to use a central struct for command execution to help with testability.
To limit the scope of the this PR it includes the use of a package level instance of the new tmux.Command struct and an init function to initialize it. Once all of the functions using the tmux cli are updated to use the Command struct directly that code can be removed in favor of a single tmux.Command instance configured in the cli.
Tested locally and ran unit tests.
=> refactor: tmux command execution

README.md, name/name.go, session/determine.go, session/path.go, tmux/list.go, tmux/list_test.go, tmux/tmux.go
Closes #77 
Support custom session names by updating the determine logic.
- Switch isSession to FindSession and return nil if not found
- Determine name logic now returns the session name if it exists
Closes #75 
Use "::" as a separator in the tmux list to support spaces in tmux path or name variables.
=> feat: improve session logic

tmux/tmux.go
Closes #80 
Use file path matching instead of a strict string matching to allow wildcard configuration values.
=> feat: support fuzzy matching on startup script

config/config.go, config/config_test.go
https://github.com/joshmedeski/sesh/pull/84#issuecomment-2021764541
```toml
default_startup_script = "default"
import = ["~/.config/sesh/local/sesh.toml"]
[[startup_scripts]]
session_path = "~/dev/first_session"
script_path = "~/.config/sesh/scripts/first_script"
[[startup_scripts]]
session_path = "~/dev/second_session"
script_path = "~/.config/sesh/scripts/second_script"
```
=> refactor(config): use `import` to replace extended_configs

README.md
Fixes the suggested tmux config to use the `sesh list -c` command/flag and adds details for listing configurations (from the 1.0.0 release notes).
=> Add config listing details to README.md

tmux/tmux.go
Closes #109 
Allows a trailing slash on the config `path` prop.
=> feat: allow path to include trailing slash

README.md
I've copied and used your example fzf-tmux script from your README.md (below)
```bash
bind-key "T" run-shell "sesh connect \"$(
sesh list | fzf-tmux -p 55%,60% \
--no-sort --border-label ' sesh ' --prompt '⚡  ' \
--header '  ^a all ^t tmux ^g configs ^x zoxide ^d tmux kill ^f find' \
--bind 'tab:down,btab:up' \
--bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list)' \
--bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t)' \
--bind 'ctrl-g:change-prompt(⚙️  )+reload(sesh list -c)' \
--bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z)' \
--bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
--bind 'ctrl-d:execute(tmux kill-session -t {})+change-prompt(⚡  )+reload(sesh list)'
)\""
```
It's great, but I've had a problem with how the row symbols are rendered... see image …
=> fix: fzf-tmux ANSI rendering example

seshcli/connect.go
fixes: https://github.com/joshmedeski/sesh/issues/114
```
 sesh connect $(sesh list -i | gum filter --limit 1 --placeholder 'Pick a session' --height 60 --prompt='⚡')
panic: runtime error: slice bounds out of range [4:3]
goroutine 1 [running]:
github.com/joshmedeski/sesh/icon.(*RealIcon).RemoveIcon(0x140001288c0?, {0x16f916fad, 0x3})
/home/runner/work/sesh/sesh/icon/icon.go:55 +0x128
github.com/joshmedeski/sesh/seshcli.App.Connect.func1(0x1400018f958?)
/home/runner/work/sesh/sesh/seshcli/connect.go:70 +0xb4
github.com/urfave/cli/v2.(*Command).Run(0x140001be2c0, 0x140001288c0, {0x14000111350, 0x3, 0x3})
/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/command.go:279 +0x754
github.com/urfave/cli/v2.(*Command).Run(0x140001be6e0, 0x14000128780, {0x14000128040, 0x4, 0x4}) …
```
=> Concatenate args to avoid out of bound issues

lister/list.go
For https://github.com/joshmedeski/sesh/issues/50
Adding the `--hide-attached` flag back to the sesh list command (hides any attached tmux session from the list).
=> feat: adding --hide-attached flag to list

.goreleaser.yaml, README.md
After a search of the AUR packages, I found that goreleaser already have published sesh to the AUR, but uses `sesh-bin` as the package name.
So I just added to the README the information on how to install it using the yay package manager.
This PR will close issue #173
=> Add Yay package manager

README.md, dir/dir.go, dir/mock_Dir.go, seshcli/connect.go, seshcli/seshcli.go
For https://github.com/joshmedeski/sesh/issues/130
Adds a `--root` flag that connects you to the root of a `.bare` worktree or git root, and ignored if not found.
This makes it easy to jump from `~/c/dotfiles/.config/neovim` to `~/c/dotfiles` with a single command. I have bound it to `<prefix>+9` in tmux by adding this to my `tmux.conf`:
```sh
bind -N "switch to root session (via sesh) " 9 run-shell "sesh connect --root \'$(pwd)\'"
```
=> Add connect root flag

tmuxinator/list.go, tmuxinator/list_test.go
Changed the tmuxinator list command to use the -n flag to seperate configs onto new lines to make cleaning the response easier
=> fix: tmuxinator list parsing

README.md
When in a Zsh shell and pressing `Alt-s`, the session list opens with FZF, thanks to the script provided in the `README`.
Pressing `Esc` or `Ctrl-C` goes back to the shell, but we need to press `Enter` again before we're given another Zsh prompt. The same issue appears when entering a tmux session: after detaching from tmux, we need to press `Enter` again before we're given another Zsh prompt.
Calling the function by typing in `sesh-session` at the Zsh prompt and pressing `Enter`, and then closing FZF already does what we want - we're given another Zsh prompt. This PR aims to replicate the same behavior through the `Alt-s` shortcut.
=> docs(readme): reset zsh prompt after calling sesh-sessions script

README.md, main.go, seshcli/seshcli.go
This PR will close issue #140 
Adds structured logger to the application
Define your logs by priority: Debug, Info, Warn and Error by adding the following to the code
```go
import log/slog
slog.Debug("Debug message")
slog.Info("Information message")
slog.Warn("Warning message")
slog.Error("Error message")
```
To set the debug level when running:
```bash
ENV=debug sesh
```
Just need to change the **debug** text for **info** or **error**. The default log level is **warn**.
=> feat: Add logger

README.md
Made some tweaks to the `tmux` example script, to display and work with icons. I find it way easier to navigate through the list of sessions this way.
=> docs(readme): improve tmux script to work with icons

lister/list.go, seshcli/list.go
This PR addresses #156 and removes duplicates based on the Path entries.
Performance time is linear wrt number of entries.
=> Remove duplicates in final list

README.md, tmux/tmux.go
When creating new tmux sessions, sesh now automatically sets the SESH_SESSION_NAME environment variable to the name of the session. This enables scripts and programs to know the current session name.
- Add -e SESH_SESSION_NAME to tmux new-session command
- Document the new feature in README.md under Environment Variables section
=> feat: add SESH_SESSION_NAME environment variable

lister/blacklist.go, lister/tmux.go
My go fu is not that high, but this works and I really have a use-case for using regex (or at least some wild-card) matching in the blacklist.
e.g.
blacklist = [
"^scratch$",
"^__"
]
I have quite some temporary popup sessions that start with __
=> feat: Support regex in blacklist

README.md, go.mod, go.sum, replacer/replacer.go, replacer/replacer_test.go, seshcli/seshcli.go, shell/shell_test.go, startup/config.go, startup/defaultconfig.go, startup/startup.go
Currently, when you use the replacement syntax `{}` in the startup command, it isn't replaced. Since I was hoping to use this as an argument that can't be passed with a space delimiting it, I needed to introduce a separate `replacer` which uses the `aho-corasick` algorithm to replace instances of the string. I included tests for the replacer and another test to assert the existing behaviour for preview commands.
This PR was made specifically to introduce the least change, but my preference (if you're happy with it) is to instead use the new `Replacer` to complete replacements in `PrepareCmd` _before_ splitting and substituting the home directory. This way we have a consistent replacement mechanism. I'm also open to the replacement mechanism being used for home directory substitution as …
=> feat: allow replacements in startup command

README.md, configurator/configurator.go, main.go, model/config.go, seshcli/seshcli.go
This prevents users from putting in invalid keys. I also made it print details of the error if the error doesn't result to nil and same with the details. This was done by not using the `toml.Unmarshal` alias and creating a Decoder manually with a strings.reader(file) 
as the argument and enabling strict marshalling to the Decoder,
=> Strict toml marshalling

connector/tmux.go
Fixes issue where command flags are being ignored when connecting to a session.
Running the following would connect to the session but would ignore the command flag:
```
./sesh connect "~/Downloads" --command "nvim"
```
The `--command` flag is not ignored when using `sesh connect`. Running the same command above connects to the session and opens `nvim`:
```
./sesh connect "~/Downloads" --command "nvim"
```
=> Fix command flag
